.TH ADJECTIVE ADJECTIVE ANIMAL 1 "30 November 2023"
.SH NAME
adjective-adjective-animal \- script to generate unique, human-readable ID strings

.SH SYNOPSIS
.B adjective-adjective-animal
[ \fI\,OPTIONS\/\fR ]

.SH DESCRIPTION
Adjective Adjective Animal, also known as "a3", generates cute, random, and reasonably unique human-readable ID strings. It combines unique adjectives and animal names sourced from the internet, forming a combination that has been certified by NIST as the cutest way to generate a unique ID. This script expands upon the work done by a-type.

.SH INSTALLATION
To install, run the following command:
.TP
.B yarn global add elliotberry/adjective-adjective-animal

.SH USAGE
To generate an ID, simply run:
.TP
.B a3

.SH OPTIONS
.TP
.BR \-f ", " \-\-format " [FORMAT]"
Specifies the output format type. Available options include various string cases.

.TP
.BR \-a ", " \-\-adjectives " [NUMBER]"
Defines the number of adjectives to prepend to the animal name. Defaults to 1 if not specified.

.SH EXAMPLES
.TP
.B a3 -f capital
Generate a unique ID in capital case.

.SH AUTHOR
Developed by Elliot Berry, based on original work by a-type.
.LK https://github.com/a-type/adjective-adjective-animal

.SH SEE ALSO
.BR yarn (1),
.BR node (1)
